CREATE TABLE WineStyle
(
	ID INT IDENTITY(1, 1) PRIMARY KEY
	, [Name] NVARCHAR(50) COLLATE Serbian_Latin_100_CI_AS UNIQUE NOT NULL 
)										  
										  
CREATE TABLE WineSort					  
(										  
	ID INT IDENTITY(1, 1) PRIMARY KEY	  
	, [Name] NVARCHAR(50) COLLATE Serbian_Latin_100_CI_AS UNIQUE  NOT NULL 
)

CREATE TABLE Wine
(
	ID INT IDENTITY(1, 1) PRIMARY KEY
	, [Name] NVARCHAR(50) COLLATE Serbian_Latin_100_CI_AS NOT NULL
	, Price MONEY NOT NULL
	, IDStyle INT NOT NULL
	, IDSort INT NOT NULL
	, CONSTRAINT FK_Wine_WineStyle FOREIGN KEY (IDStyle) REFERENCES WineStyle(ID)
	, CONSTRAINT FK_Wine_WineSort FOREIGN KEY (IDSort) REFERENCES WineSort(ID)
)

CREATE TABLE Cart
(
	ID INT IDENTITY(1, 1) PRIMARY KEY
	, Total MONEY NOT NULL
)

CREATE TABLE CartItems
(
	IDCart INT
	, IDWine INT
	, Quantity INT NOT NULL
	, Total MONEY NOT NULL
	, CONSTRAINT PK_CartItems PRIMARY KEY (IDCart, IDWine)
	, CONSTRAINT FK_CartItems_Cart FOREIGN KEY (IDCart) REFERENCES Cart(ID)
	, CONSTRAINT FK_CartItems_Wine FOREIGN KEY (IDWine) REFERENCES Wine(ID)
)
